### ISSUE TITLE
Test/Sandbox URL fails

### ISSUE THREAD

**Issue by hlushko** [PaySys/CardPay#5]
Hello.

Excuse me for possible not related question, but I hope that you can help me.

During testing TatraBanka CardPay logic, I found that test env doesn't work...

Using test values:

> mid: 9999

> secret: 31323334353637383930313233343536373839303132333435363738393031323132333435363738393031323334353637383930313233343536373839303132

I received such URL:

> https://moja.tatrabanka.sk/cgi-bin/e-commerce/start/example?MID=9999&AMT=12345.67&CURR=978&VS=123456720&RURL=http%3A%2F%2Fcp.local%2Fcart%2Fpayment%2Fconfirm%2Ftatrabanka&IPC=172.30.0.1&NAME=John+Doe&REM=serhii%40realpadsoftware.com&TIMESTAMP=24092019092851&HMAC=1b06f4919e995a1993661ce9797689d71dafcf0f29626f1c5110c01e4726161b&AREDIR=1&LANG=en

But if fails with 500 error.

If I use prod endpoint: https://moja.tatrabanka.sk/cgi-bin/e-commerce/start/cardpay with same data it returns me an error: "Payment can not be made because of an invalid security signature.", although HMAC tester (https://moja.tatrabanka.sk/cgi-bin/e-commerce/start/example) provides me same HMAC value as I sent to it...

Maybe you saw such behavior before and have any information?

**Comment by romanmatyus** [comment]
@hlushko Look at test/src files in this repo. By error, you have wrong signature. Fix it by my code :)
